"""empty message

Revision ID: 7289e92a03db
Revises: 99aa4ba8df92
Create Date: 2025-02-16 11:44:40.470899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7289e92a03db'
down_revision = '99aa4ba8df92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('assessment_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('GENERAL', 'CENTER_PROMOTION', 'OUTREACH_PROMOTION', name='assessmenttype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('assessment_type',
               existing_type=sa.Enum('GENERAL', 'CENTER_PROMOTION', 'OUTREACH_PROMOTION', name='assessmenttype'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
