"""empty message

Revision ID: 98f6b165d3b0
Revises: 7289e92a03db
Create Date: 2025-02-16 12:42:14.053706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f6b165d3b0'
down_revision = '7289e92a03db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
