"""empty message

Revision ID: 99aa4ba8df92
Revises: 5795fc8cf325
Create Date: 2025-02-16 11:19:46.694003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99aa4ba8df92'
down_revision = '5795fc8cf325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_session', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('term', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('center_class', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_graduating', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('is_graduating')
        batch_op.drop_column('center_class')
        batch_op.drop_column('term')
        batch_op.drop_column('academic_session')

    # ### end Alembic commands ###
